name: C++ CI/CD Pipeline (cppcheck)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-package:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:

    - name: Run cppcheck Static Analysis
      run: |
        cppcheck --enable=warning,style,performance,portability \
          --suppress=shadowVariable \
          --error-exitcode=1 \
          src/

